services:
  webhook:
    build: .
    container_name: webhook_local
    env_file:
      - .env
    # volumes:
    #   - ./opt/deploy:/opt/deploy
    volumes:
      - ./opt/deploy:/opt/deploy
      - /root/crm_back:/root/crm_back
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:8000"
